disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
opt_in_rules: # some rules are only opt-in
- empty_count
- force_unwrapping
included: # paths to include during linting. `--path` is ignored if present.
- ItunesArtistCollection
excluded: # paths to ignore during linting. Takes precedence over `included`.
- DerivedData
